# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kalu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kalu

  target 'Kalu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KaluTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Kalu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kalu-tvOS

  target 'Kalu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
