export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING'

export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS'

export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR'

export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE'

export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'

export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'

export const SET_AUDIO_NAME = 'SET_AUDIO_NAME'

export const SET_WATSON_RESPONSE = 'SET_WATSON_RESPONSE'

export const SET_RECORDING_STATUS = 'SET_RECORDING_STATUS'

export const SET_TRANSACTION_DATA = 'SET_TRANSACTION_DATA'

export const SET_TRANSACTION_DETAIL_STATE = 'SET_TRANSACTION_DETAIL_STATE'

export const GET_INCOME_PIE_DATA = 'GET_INCOME_PIE_DATA'

export const GET_EXPENSE_PIE_DATA ='GET_EXPENSE_PIE_DATA'
