export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING'

export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS'

export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR'

export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE'

export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'

export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'

export const SET_AUDIO_NAME = 'SET_AUDIO_NAME'

export const SET_WATSON_RESPONSE = 'SET_WATSON_RESPONSE'

export const SET_RECORDING_STATUS = 'SET_RECORDING_STATUS'
